name: "Invite to organisation"
description: "Invite contributors to organisation"

inputs:
  organisation:
    description: "Organisation name"
    required: true
  team:
    description: "Team name"
    required: true
  github-token:
    description: "Github Token"
    required: true

runs:
  using: "composite"
  steps:
    # - name: Get PR info
    #   id: get-info
    #   uses: strawberry-graphql/get-pr-info-action@main
    - uses: actions/github-script@v4
      env:
        ORGANISATION: ${{ inputs.organisation }}
        TEAM: ${{ inputs.team }}
        PR_NUMBER: "2"  #${{ steps.get-info.outputs.pr-number }}
        ACCESS_TOKEN: ${{ inputs.github-token }}
      with:
        script: |
          const script = require('./main.js')
          await script({github, context, core})