name: "Invite to organisation"
description: "Invite contributors to organisation"

inputs:
  organisation:
    description: "Organisation name"
    required: true
  team:
    description: "Team name"
    required: true

runs:
  using: "composite"
  steps:
    - name: Get PR info
      id: get-info
      uses: strawberry-graphql/get-pr-info-action@main
    - uses: actions/github-script@v4
      env:
        ORGANISATION: ${{ inputs.organisation }}.
        TEAM: ${{ inputs.team }}.
        PR_NUMBER: ${{ steps.get-info.outputs.pr-number }}.
      with:
        script: |
          const script = require('./main.js')
          await script({github, context, core})