name: "Invite to organisation"
description: "Invite contributors to organisation"

inputs:
  organisation:
    description: "Organisation name"
    required: true
  team-slug:
    description: "Team slug"
    required: true
  github-token:
    description: "Github Token"
    required: true
  comment:
    description: "Comment message"
    required: true

runs:
  using: "composite"
  steps:
    - name: Get PR info
      id: get-info
      uses: strawberry-graphql/get-pr-info-action@v2
      env:
        ACCESS_TOKEN: ${{ inputs.github-token }}
    - uses: actions/github-script@v4
      env:
        ORGANISATION: ${{ inputs.organisation }}
        TEAM_SLUG: ${{ inputs.team-slug }}
        USERNAME: ${{ steps.get-info.outputs.contributor-username }}
        REPOSITORY_NAME: ${{ steps.get-info.outputs.repository-name }}
        PR_NUMBER: ${{ steps.get-info.outputs.pr-number }}
        COMMENT: ${{ inputs.comment }}
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const script = require('${{ github.action_path }}/main.js')
          await script({github, context, core})
