on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: ./
        with:
          organisation: strawberry-graphql
          team: strawberry-contributors
          comment: |
            Hi there! Thanks for the PR. You have now been invited to the organisation!
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
